# Generated by Django 5.0.6 on 2024-05-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Produto')),
            ],
        ),
    ]
