# Generated by Django 5.0.6 on 2024-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='foto',
            field=models.ImageField(default=True, upload_to='foto_perfil/'),
        ),
    ]
