# Generated by Django 5.0.4 on 2024-04-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='perfil/')),
                ('documentos', models.FileField(upload_to='documentos/')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parte2.aluno')),
            ],
        ),
    ]
