# Generated by Django 5.0.6 on 2024-06-25 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('celular', models.PositiveIntegerField()),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_da_peca', models.IntegerField()),
                ('nome_da_peca', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdemNumero', models.PositiveIntegerField()),
                ('data', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pecas', models.CharField(max_length=100, verbose_name='Peças')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garagem.veiculos')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_Total', models.IntegerField()),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garagem.mecanicos', verbose_name='Mecânico')),
                ('valor_do_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garagem.ordemservico', verbose_name='Valor do Serviço')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garagem.veiculos')),
            ],
        ),
    ]
