# Generated by Django 5.0.6 on 2024-06-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecas',
            old_name='nome_da_peca',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='pecas',
            name='id_da_peca',
        ),
    ]
