# Generated by Django 5.0.6 on 2024-05-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('Ano_fabricacao', models.DateField()),
                ('Km', models.IntegerField()),
                ('Preço', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Matricula', models.IntegerField()),
                ('Carro', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CarrosOnline.carros')),
            ],
        ),
    ]
