# Generated by Django 5.0.7 on 2024-07-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=20, verbose_name='CPF:')),
                ('end', models.CharField(max_length=100, verbose_name='Endereço:')),
            ],
        ),
        migrations.CreateModel(
            name='Sapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='foto_media/')),
                ('marca', models.CharField(max_length=100)),
                ('tamanho', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sapataria.cliente')),
                ('produtos', models.ManyToManyField(to='Sapataria.sapato')),
            ],
        ),
    ]
