# Generated by Django 5.0.6 on 2024-05-17 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('E_Mail', models.EmailField(max_length=254, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('Matricula', models.IntegerField()),
                ('Cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_produto', models.CharField(max_length=100)),
                ('Descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('secao', models.CharField(max_length=10, verbose_name='Seção')),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_Transportadora', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('fone', models.IntegerField(verbose_name='Celular')),
                ('E_Mail', models.EmailField(max_length=254, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_do_pedido', models.DateField()),
                ('valor', models.FloatField()),
                ('Numero_do_Pedido', models.IntegerField()),
                ('Vendedor', models.ManyToManyField(to='Bancos_Bd.funcionario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bancos_Bd.clientes')),
                ('produto', models.ManyToManyField(to='Bancos_Bd.produtos')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bancos_Bd.transportadora')),
            ],
        ),
    ]
