# Generated by Django 5.0.6 on 2024-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bancos_Bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='Data_do_pedido',
            field=models.DateField(auto_now=True),
        ),
    ]
