# Generated by Django 5.0.6 on 2024-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(default=True, upload_to='foto_perfil/'),
        ),
    ]
