# Generated by Django 5.0.6 on 2024-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='cpf',
            field=models.PositiveIntegerField(verbose_name='CPF'),
        ),
    ]
