# Generated by Django 5.0.6 on 2024-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0002_alter_cadastros_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastros',
            name='E_mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
    ]
