# Generated by Django 5.0.6 on 2024-05-16 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_alter_cadastros_e_mail_alter_cadastros_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habilidade', models.CharField(max_length=100)),
                ('Nota', models.IntegerField()),
                ('nomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.cadastros')),
            ],
        ),
    ]
