# Generated by Django 5.0.6 on 2024-05-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome:')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('end', models.CharField(max_length=100, verbose_name='Endereço')),
                ('cpf', models.PositiveIntegerField(verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('dataEntrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('contato', models.CharField(max_length=50, verbose_name='Contato')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('produto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataEntrada', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Madeiras.estoque')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Madeiras.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.IntegerField()),
                ('dataCompra', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Madeiras.clientes')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Madeiras.produtos')),
            ],
        ),
    ]
