# Generated by Django 5.0.6 on 2024-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Madeiras', '0002_alter_estoque_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(default=True, upload_to='foto_perfil/'),
        ),
    ]
