# Generated by Django 5.0.6 on 2024-06-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('foto', models.ImageField(default=True, upload_to='foto_perfil/')),
            ],
        ),
    ]
