# Generated by Django 5.0.6 on 2024-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='celular',
            field=models.IntegerField(default=True),
        ),
    ]
