# Generated by Django 5.0.6 on 2024-06-21 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_pedido_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.clientes'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.carros'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.pagamento'),
        ),
    ]
