# Generated by Django 5.0.6 on 2024-06-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0005_alter_pedido_cliente_remove_pedido_modelo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro',
            new_name='cadastro_funcionarios',
        ),
    ]
