# Generated by Django 5.0.6 on 2024-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0006_rename_cadastro_cadastro_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_funcionarios',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
