# Generated by Django 5.0.6 on 2024-06-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('E_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
    ]
