# Generated by Django 5.0.6 on 2024-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('professor', models.CharField(max_length=100)),
                ('aula_status', models.CharField(choices=[('y', 'Assistida'), ('n', 'Não assistida')], max_length=2)),
                ('valor_aula', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
