# Generated by Django 5.0.4 on 2024-04-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='sobreVoce',
            new_name='sobre_voce',
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=100)),
                ('livros_produzidos', models.ManyToManyField(to='teste.livro')),
            ],
        ),
    ]
