# Generated by Django 5.0.4 on 2024-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_rename_pcd_pessoa_possui_filhos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_e_hora',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_de_criacao',
            field=models.DateTimeField(null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='possui_filhos',
            field=models.BooleanField(default=False, verbose_name='Possui filho(s)?'),
        ),
    ]
