# Generated by Django 5.0.6 on 2024-05-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=100)),
                ('Editora', models.CharField(max_length=80)),
                ('Ano_Publicacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=80)),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Festa.autor')),
            ],
        ),
    ]
