# Generated by Django 5.0.6 on 2024-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Festa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='artigo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
