# Generated by Django 5.0.6 on 2024-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_perfil/')),
                ('fabricacao', models.DateField()),
                ('produtora', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=100)),
            ],
        ),
    ]
