# Generated by Django 5.0.6 on 2024-05-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default='', max_length=50),
        ),
    ]
