# Generated by Django 5.0.6 on 2024-05-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro_autor_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
