# Generated by Django 5.0.6 on 2024-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_livro_editora2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
